%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: PropellerEfficiencyCurves.xlsx
%    Worksheet: KT_KQ
%
% Auto-generated by MATLAB on 30-Jul-2020 12:00:00

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "KT_KQ";
opts.DataRange = "A7:J53";

% Specify column names and types
opts.VariableNames = ["CTstuv", "st", "tt", "ut", "vt", "CQstuv", "sq", "tq", "uq", "vq"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
tbl = readtable("PropellerEfficiencyCurves.xlsx", opts, "UseExcel", false);

%% Convert to output type to vectors and get rid of the NaNs
CTstuv = tbl.CTstuv(~isnan(tbl.CTstuv));
st = tbl.st(~isnan(tbl.st));
tt = tbl.tt(~isnan(tbl.tt));
ut = tbl.ut(~isnan(tbl.ut));
vt = tbl.vt(~isnan(tbl.vt));
CQstuv = tbl.CQstuv;
sq = tbl.sq;
tq = tbl.tq;
uq = tbl.uq;
vq = tbl.vq;

%% Clear temporary variables
clear opts tbl